# Generated by Django 4.1.5 on 2023-01-25 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('country', models.CharField(max_length=50, verbose_name='страна')),
                ('city', models.CharField(max_length=50, verbose_name='город')),
                ('street', models.CharField(max_length=100, verbose_name='улица')),
                ('house', models.CharField(blank=True, max_length=15, verbose_name='номер дома')),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Список контактов',
            },
        ),
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='название')),
                ('debt', models.FloatField(default=0.0, verbose_name='задолженность поставщику')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organizations.contact', verbose_name='контакты')),
            ],
            options={
                'verbose_name': 'Завод',
                'verbose_name_plural': 'Заводы',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='Модель')),
                ('created', models.DateTimeField(verbose_name='Дата выхода продукта на рынок')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Список продуктов',
            },
        ),
        migrations.CreateModel(
            name='Retail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='название')),
                ('debt', models.FloatField(default=0.0, verbose_name='задолженность поставщику')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organizations.contact', verbose_name='контакты')),
                ('product', models.ManyToManyField(to='organizations.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.factory', verbose_name='поставщик')),
            ],
            options={
                'verbose_name': 'Розничная сеть',
                'verbose_name_plural': 'Розничные сети',
            },
        ),
        migrations.AddField(
            model_name='factory',
            name='product',
            field=models.ManyToManyField(to='organizations.product'),
        ),
        migrations.CreateModel(
            name='Entrepreneur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='название')),
                ('debt', models.FloatField(default=0.0, verbose_name='задолженность поставщику')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organizations.contact', verbose_name='контакты')),
                ('product', models.ManyToManyField(to='organizations.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.retail', verbose_name='поставщик')),
            ],
            options={
                'verbose_name': 'Индивидуальный предприниматель',
                'verbose_name_plural': 'Индивидуальные предприниматели',
            },
        ),
    ]
